### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by lborensky** [kodokojo/kodokojo#16] opened 2016-07-01 10:18 UTC
Bonjour,

J'ai systématiquement l'erreur suivante suite aux actions de téléchargement des images (de base) Docker et de construction de kojokodo et kodokojo-ui.

$ ./quickstart.sh <CR>
…
./assets/images/brick-jenkins.svg
./assets/images/status-failure-small.svg
./assets/images/status-starting-small.gif
./assets/images/brick-docker-registry.svg
./assets/images/logo-white-kodokojo.svg
./assets/images/status-default-small.svg
9cff015ee1b4ff36cb22a65052a73c72deda5bd0d33489481b3117249430fb7c
**mkdir: cannot create directory ‘static’: File exists
tar (child): kodokojo-ui-0.1.0.tar.gz: Cannot open: No such file or directory**
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
$ 

Avez-vous une idée du dysfonctionnement ?

Merci.

**Comment by jpthiery** [comment] 2016-07-01 12:30
I have identify the issue and fix it.
I ust run all tests before commit the fix.

**Comment by jpthiery** [comment] 2016-07-01 12:51
Fix in https://github.com/kodokojo/kodokojo-ui/pull/11.

I close it now, but if you have another trouble we can reopen it.

**Comment by lborensky** [comment] 2016-07-04 05:21
Bonjour,

A priori, j'avais pensé que le BUILD était OK, mais après avoir lancé la
commande "docker-compose ...", depuis l'interface UI après connexion et
création d'un projet, aucune brique (gitlab, jenkins, etc.) ne semble
démarrée. Les traces après le build sont les suivantes et semblent liées à
un dysfonctionnement relatif au répertoire $HOME/kodokojo trouvé par l'un
des containers.

Sending build context to Docker daemon 1.868 MB
Step 1 : FROM nginx:1.9
 ---> c8c29d842c09
Step 2 : ADD nginx.conf.tpl /etc/nginx/nginx.conf.tpl
 ---> afde32a3e08b
Removing intermediate container fcd3888654a7
Step 3 : ADD proxy.conf /etc/nginx/proxy.conf
 ---> 2b2b9114edc5
Removing intermediate container ae054aee3f7c
Step 4 : ADD start.sh /start.sh
 ---> e073ba63a7af
Removing intermediate container e393d559f334
Step 5 : RUN chmod +x /start.sh
 ---> Running in 8308b9a7d07d
 ---> 404a521ecdac
Removing intermediate container 8308b9a7d07d
Step 6 : ADD static/ /var/www/
 ---> 7d7c48086786
Removing intermediate container 60644b1fcabe
Step 7 : CMD /start.sh
 ---> Running in fbc300a1e193
 ---> 1b8bff057019
Removing intermediate container fbc300a1e193
Successfully built 1b8bff057019
~/kodokojo
docker: Error response from daemon: Invalid volume spec ":": Invalid
volume specification: ':'.

See 'docker run --help'.

A vrai dire, je cherche (simplement) à reproduire, à minima, la fonction
première de la solution. Merci de votre retour.

Cdlt,


2016-07-01 14:51 GMT+02:00 Jean-Pascal THIERY <notifications@github.com>:

**Comment by jpthiery** [comment] 2016-07-04 10:03
Could you please provide us your commadn step. Do you meet this issue while building Kodo Kojo with `quickstart.sh`or while trying to create a software factory ?

**Comment by ctranxuan** [comment] 2016-07-08 15:45
Got the same issue. Having a look at `build.sh`, I guess that it comes from the fact that the environment variable `DOCKER_CERT_PATH` is set nowhere.

I've tried to set this environment variable to the path of the project:

```
git clone https://github.com/kodokojo/kodokojo.git
cd kodokojo
export DOCKER_CERT_PATH=$PWD
./quickstart.sh
```

This seems to work a bit more far but now I've got the following error:

```
Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project kodokojo: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]
```
<details>
[INFO] --- maven-dependency-plugin:2.8:copy (copy-jar-to-dockerfile) @ kodokojo ---
[INFO] Configured Artifact: io.kodokojo:kodokojo:runnable:0.1.0-SNAPSHOT:jar
[INFO] Copying kodokojo-0.1.0-SNAPSHOT-runnable.jar to /usr/src/mymaven/target/docker/kodokojo.jar
[INFO] 
[INFO] --- docker-maven-plugin:0.3.258:build (default) @ kodokojo ---
[INFO] Copying /usr/src/mymaven/src/main/docker/local/Dockerfile -> /usr/src/mymaven/target/docker/Dockerfile
[INFO] Building image kodokojo/kodokojo
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.562 s
[INFO] Finished at: 2016-07-08T15:40:09+00:00
[INFO] Final Memory: 41M/1077M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project kodokojo: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
</details>

**Comment by jpthiery** [comment] 2016-07-11 07:42
@ctranxuan I create a new issue, yours not seems to get same root cause. See #20.

**Comment by ctranxuan** [comment] 2016-07-11 15:32
Hi,
This time, I've got another issue:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2016-07-11T14:55:50+00:00
[INFO] Final Memory: 15M/207M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kodokojo: Could not resolve dependencies for project io.kodokojo:kodokojo:jar:0.1.0-SNAPSHOT: Could not find artifact io.kodokojo:kodokojo-commons-tests:jar:0.1.0-SNAPSHOT in jitpack.io (https://jitpack.io) -> [Help 1]
```

I've still used the workaround:
```export DOCKER_CERT_PATH=$PWD```

**Comment by jpthiery** [comment] 2016-07-11 15:40
Hi, 

I have merge `commons`and `commons-test`project in Kodo Kojo today which aren't requiered anymore.

I have forget to remove commons-test dependencies...
I remove this now from the `pom.xml`, running my tests and commit this.

export `DOCKER_CERT_PATH` may not requiered anymore too.

**Comment by jpthiery** [comment] 2016-07-13 14:57
PR #25 may solve this issue.

**Closed by jpthiery** 2016-07-13 14:57 UTC
Labels: bug
